-- Crear tabla para pre-reservas
CREATE TABLE IF NOT EXISTS pre_reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  celular TEXT NOT NULL,
  opcion_elegida TEXT NOT NULL, -- 'opcion1', 'opcion2', 'opcion3'
  precio_original INTEGER NOT NULL,
  precio_descuento INTEGER NOT NULL,
  descuento_porcentaje INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(celular)
);

-- Habilitar Row Level Security
ALTER TABLE pre_reservas ENABLE ROW LEVEL SECURITY;

-- Política para insertar pre-reservas (público)
CREATE POLICY "Public insert pre_reservas" ON pre_reservas FOR INSERT WITH CHECK (true);

-- Política para leer pre-reservas (público)
CREATE POLICY "Public read pre_reservas" ON pre_reservas FOR SELECT USING (true);

-- Función para calcular descuento de ruleta (35% hacia abajo a partir del 17/05/2026)
CREATE OR REPLACE FUNCTION calculate_ruleta_descuento(celular TEXT)
RETURNS TABLE(discount_percent INTEGER, discounted_price INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  base_price INTEGER := 60;
  random_val INTEGER;
BEGIN
  -- Generar un valor aleatorio entre 0 y 100
  random_val := FLOOR(RANDOM() * 101);
  
  -- Si el valor es menor que 35, aplicar descuento
  IF random_val < 35 THEN
    -- Descuento variable de 35% hacia abajo
    DECLARE
      discount_base INTEGER := 35;
      actual_discount INTEGER := FLOOR(RANDOM() * (discount_base + 1));
    BEGIN
      RETURN QUERY SELECT actual_discount, FLOOR(base_price * (100 - actual_discount) / 100)::INTEGER;
    END;
  ELSE
    -- No hay descuento (0%)
    RETURN QUERY SELECT 0, base_price;
  END IF;
END;
$$;

-- Índice para búsquedas rápidas por celular
CREATE INDEX IF NOT EXISTS idx_pre_reservas_celular ON pre_reservas(celular);
