-- Crear tabla app_info
CREATE TABLE IF NOT EXISTS app_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  tagline TEXT NOT NULL,
  description TEXT NOT NULL,
  windows_url TEXT,
  android_url TEXT,
  version TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear tabla features
CREATE TABLE IF NOT EXISTS features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  icon TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  show_on_page BOOLEAN DEFAULT true,
  show_on_modal BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear tabla download_stats
CREATE TABLE IF NOT EXISTS download_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(platform)
);

-- Crear función para incrementar descargas
CREATE OR REPLACE FUNCTION increment_download(_platform TEXT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO download_stats (platform, count)
  VALUES (_platform, 1)
  ON CONFLICT (platform)
  DO UPDATE SET count = download_stats.count + 1, updated_at = NOW();
END;
$$;

-- Insertar datos iniciales de app_info
INSERT INTO app_info (name, tagline, description, windows_url, android_url, version)
VALUES (
  'bitly',
  'Tu música, sin límites',
  'Descarga bitly: música FLAC sin pérdida desde Tidal, Qobuz, Deezer y más. Disponible para Windows y Android.',
  'https://github.com/QuopTron',
  'https://github.com/QuopTron',
  '1.0.0'
) ON CONFLICT DO NOTHING;

-- Insertar características iniciales
-- Seed features: show on main page
INSERT INTO features (title, description, icon, sort_order, show_on_page, show_on_modal) VALUES
  ('Descarga FLAC sin pérdida', 'Obtén la máxima calidad de audio de Tidal, Qobuz y Deezer', 'Music', 1, true, false),
  ('Multiplataforma', 'Disponible para Windows y Android con sincronización', 'Layers', 2, true, false),
  ('Interfaz moderna', 'Diseño limpio y fácil de usar con modo oscuro', 'Sparkles', 3, true, false),
  ('Búsqueda inteligente', 'Encuentra cualquier canción o álbum rápidamente', 'Search', 4, true, false),
  ('Listas de reproducción', 'Organiza tu música en listas personalizadas', 'ListMusic', 5, true, false),
  ('Etiquetas y metadatos', 'Información completa de cada pista', 'Tags', 6, true, false)
ON CONFLICT DO NOTHING;

-- Insertar estadísticas iniciales
INSERT INTO download_stats (platform, count) VALUES
  ('windows', 0),
  ('android', 0)
ON CONFLICT DO NOTHING;

-- Habilitar Row Level Security
ALTER TABLE app_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE features ENABLE ROW LEVEL SECURITY;
ALTER TABLE download_stats ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para lectura pública
CREATE POLICY "Public read app_info" ON app_info FOR SELECT USING (true);
CREATE POLICY "Public read features" ON features FOR SELECT USING (true);
CREATE POLICY "Public read download_stats" ON download_stats FOR SELECT USING (true);

-- Política para insertar en download_stats (para el contador)
CREATE POLICY "Public insert download_stats" ON download_stats FOR INSERT WITH CHECK (true);

-- Política para actualizar download_stats (para el contador)
CREATE POLICY "Public update download_stats" ON download_stats FOR UPDATE USING (true);
