name = "bitly-site"
type = "javascript"
account_id = "a5e62a1e8ae4840916ed4122689e507c"
workers_dev = true
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"

[build.upload]
format = "service-worker"

# ✅ Corregido: ruta real de salida de Vite
pages_build_output_dir = "dist/client"

[site]
bucket = "dist/client"
entry-point = "src"


