import fs from "node:fs";
const h = fs.readFileSync("dist/client/index.html", "utf8");
const g = (re) => { const m = h.match(re); return m ? m[0].slice(0, 200) : "AUSENTE"; };
console.log("title     :", g(/<title>[^<]*<\/title>/));
console.log("canonical :", g(/<link rel="canonical"[^>]*>/));
console.log("desc      :", g(/<meta name="description"[^>]*>/));
console.log("og:image  :", g(/<meta property="og:image"[^>]*>/));
console.log("og:title  :", g(/<meta property="og:title"[^>]*>/));
console.log("twitter   :", g(/<meta name="twitter:card"[^>]*>/));
console.log("robots    :", g(/<meta name="robots"[^>]*>/));
console.log("theme-color:", (h.match(/<meta name="theme-color"[^>]*>/g) || []).join(" "));
console.log("jsonld    :", (h.match(/<script type="application\/ld\+json">/g) || []).length, "bloques");
console.log("h1/h2/det :", (h.match(/<h1[ >]/g) || []).length, "/", (h.match(/<h2[ >]/g) || []).length, "/", (h.match(/<details[ >]/g) || []).length);
console.log("manifest  :", g(/<link rel="manifest"[^>]*>/));
console.log("favicon   :", (h.match(/<link rel="icon"[^>]*>/g) || []).length + (h.match(/<link rel="apple-touch-icon"[^>]*>/g) || []).length, "etiquetas");
console.log("googfonts :", h.includes("fonts.googleapis"), "| spinner/cargando:", /Cargando|Loading/i.test(h));
console.log("font-preload:", g(/<link rel="preload" href="\/fonts\/[^>]*>/));
console.log("faq visible:", h.includes('id="faq"'), "| h1 contiene musica:", /Tu m.sica/.test(h));
console.log("bytes:", h.length);
